### ISSUE TITLE
`isUpdateNeededForSystem` always returns `true`

### ISSUE THREAD

**Issue by arnaud-secondlayer** [denniskaselow/dartemis#58]
I made the simple test at the bottom and when I put a breakpoint in `World._updateSystem`, I can see that `componentManager.isUpdateNeededForSystem(system)` returns `true` for the first call to `world.process` (expected), but also for the second call, which I was not expected because my entity hasn't changed.
This has performance consequences because the list of entities sent to every system has to be constantly rebuilt.

```
library world_test;

import 'package:dartemis/dartemis.dart';
import 'package:test/test.dart';

void main() {
  group('System tests', () {
    test('Simple test ', () {
      final world = World();
      world.addSystem(MySystem_0());

      world.createEntity([MyComponent_0()]);

      world.process();
      world.process();

      expect(true, isTrue);
    });
  });
}

class MyComponent_0 extends Component {}

class MySystem_0 extends EntitySystem {
  MySystem_0() : super(Aspect.forAllOf([MyComponent_0]));

  @override
  bool checkProcessing() => true;

  @override
  void processEntities(Iterable<int> entities) {
    print(entities);
  }
}
```

**Comment by denniskaselow** [comment]
Well, that's embarrassing as that part was pretty much the point of version 0.9.0.

Thank you very much for discovering this bug. I have no idea how I missed that...

A new version 0.9.4 has been published.
